FROM oven/bun:1

ARG DATABASE_URL

WORKDIR /usr/src/app

COPY . .

RUN bun install

RUN bun run generate:db

RUN echo ${secrets.DATABASE_URL}
ENV DATABASE_URL=${secrets.DATABASE_URL}
RUN bun run build

EXPOSE 3000

CMD [ "bun","start:frontend" ]