FROM oven/bun:1

ARG DB_URL

WORKDIR /usr/src/app

COPY . .

RUN bun install

RUN bun run generate:db

RUN echo ${DATABASE_URL}
ENV DATABASE_URL=${DATABASE_URL}
RUN bun run build

EXPOSE 3000

CMD [ "bun","start:frontend" ]