FROM oven/bun:1

ARG DATABASE_URL

WORKDIR /usr/src/app

COPY . .

RUN bun install

RUN bun run generate:db

RUN DATABASE_URL=${DATABASE_URL} bun run build

EXPOSE 3000

CMD [ "bun","start:frontend" ]